name: Publish

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get next version
        id: nbgv
        shell: pwsh
        run: |
            dotnet tool restore
            $version = (dotnet nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
            "PODESERVER_VERSION=$version" | Set-Content $env:GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{steps.nbgv.outputs.PODESERVER_VERSION}}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/PodeServer:latest,${{ vars.DOCKERHUB_USERNAME }}/PodeServer:${{steps.nbgv.outputs.PODESERVER_VERSION}}
